# Generated by Django 4.1.6 on 2023-07-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon_souls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
