# Generated by Django 4.1.6 on 2023-07-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demon_souls', '0002_customuser_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_banned',
        ),
    ]
