# Generated by Django 4.1.6 on 2023-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon_souls', '0003_remove_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
