# Generated by Django 4.2.1 on 2023-07-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon_souls', '0004_comment_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attack_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('special', 'Special'), ('magic', 'Magic')], default='standard', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='str',
            field=models.IntegerField(default=0),
        ),
    ]
